// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSKpD5ev1CM5jK72hvh84W6dmKC9EudEk',
    appId: '1:1047665890758:web:530c107ef9e8087a160ec7',
    messagingSenderId: '1047665890758',
    projectId: 'app-consultas-4fb55',
    authDomain: 'app-consultas-4fb55.firebaseapp.com',
    storageBucket: 'app-consultas-4fb55.appspot.com',
    measurementId: 'G-WDMJDGHWDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWwyA6Y46nzTBAknBIJLqAPXM9pCu1Sug',
    appId: '1:1047665890758:android:17769c05e1daba44160ec7',
    messagingSenderId: '1047665890758',
    projectId: 'app-consultas-4fb55',
    storageBucket: 'app-consultas-4fb55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUwfJua9c23myp29PqfUPZA_iDBbdyFGo',
    appId: '1:1047665890758:ios:11ae0a7f35ff8b24160ec7',
    messagingSenderId: '1047665890758',
    projectId: 'app-consultas-4fb55',
    storageBucket: 'app-consultas-4fb55.appspot.com',
    iosBundleId: 'com.example.consultaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUwfJua9c23myp29PqfUPZA_iDBbdyFGo',
    appId: '1:1047665890758:ios:ffa49d317735bda5160ec7',
    messagingSenderId: '1047665890758',
    projectId: 'app-consultas-4fb55',
    storageBucket: 'app-consultas-4fb55.appspot.com',
    iosBundleId: 'com.example.consultaApp.RunnerTests',
  );
}
